#ifndef _INSTRS_H
#define _INSTRS_H

#define NUM_OPS 0x100

typedef int (*op) ();

int not_implemented();

//
//  Basic instruction set
//

int  RLC_B();            // 0x00
int  RLC_C();            // 0x01
int  RLC_D();            // 0x02
int  RLC_E();            // 0x03
int  RLC_H();            // 0x04
int  RLC_L();            // 0x05
int  RLC_HL();           // 0x06
int  RLC_A();            // 0x07
int  RRC_B();            // 0x08
int  RRC_C();            // 0x09
int  RRC_D();            // 0x0a
int  RRC_E();            // 0x0b
int  RRC_H();            // 0x0c
int  RRC_L();            // 0x0d
int  RRC_HL();           // 0x0e
int  RRC_A();            // 0x0f
int  RL_B();             // 0x10
int  RL_C();             // 0x11
int  RL_D();             // 0x12
int  RL_E();             // 0x13
int  RL_H();             // 0x14
int  RL_L();             // 0x15
int  RL_HL();            // 0x16
int  RL_A();             // 0x17
int  RR_B();             // 0x18
int  RR_C();             // 0x19
int  RR_D();             // 0x1a
int  RR_E();             // 0x1b
int  RR_H();             // 0x1c
int  RR_L();             // 0x1d
int  RR_HL();            // 0x1e
int  RR_A();             // 0x1f
int  SLA_B();            // 0x20
int  SLA_C();            // 0x21
int  SLA_D();            // 0x22
int  SLA_E();            // 0x23
int  SLA_H();            // 0x24
int  SLA_L();            // 0x25
int  SLA_HL();           // 0x26
int  SLA_A();            // 0x27
int  SRA_B();            // 0x28
int  SRA_C();            // 0x29
int  SRA_D();            // 0x2a
int  SRA_E();            // 0x2b
int  SRA_H();            // 0x2c
int  SRA_L();            // 0x2d
int  SRA_HL();           // 0x2e
int  SRA_A();            // 0x2f
int  SWAP_B();           // 0x30
int  SWAP_C();           // 0x31
int  SWAP_D();           // 0x32
int  SWAP_E();           // 0x33
int  SWAP_H();           // 0x34
int  SWAP_L();           // 0x35
int  SWAP_HL();          // 0x36
int  SWAP_A();           // 0x37
int  SRL_B();            // 0x38
int  SRL_C();            // 0x39
int  SRL_D();            // 0x3a
int  SRL_E();            // 0x3b
int  SRL_H();            // 0x3c
int  SRL_L();            // 0x3d
int  SRL_HL();           // 0x3e
int  SRL_A();            // 0x3f
int  test_bit_0_B();     // 0x40
int  test_bit_0_C();     // 0x41
int  test_bit_0_D();     // 0x42
int  test_bit_0_E();     // 0x43
int  test_bit_0_H();     // 0x44
int  test_bit_0_L();     // 0x45
int  test_bit_0_HL();    // 0x46
int  test_bit_0_A();     // 0x47
int  test_bit_1_B();     // 0x48
int  test_bit_1_C();     // 0x49
int  test_bit_1_D();     // 0x4a
int  test_bit_1_E();     // 0x4b
int  test_bit_1_H();     // 0x4c
int  test_bit_1_L();     // 0x4d
int  test_bit_1_HL();    // 0x4e
int  test_bit_1_A();     // 0x4f
int  test_bit_2_B();     // 0x50
int  test_bit_2_C();     // 0x51
int  test_bit_2_D();     // 0x52
int  test_bit_2_E();     // 0x53
int  test_bit_2_H();     // 0x54
int  test_bit_2_L();     // 0x55
int  test_bit_2_HL();    // 0x56
int  test_bit_2_A();     // 0x57
int  test_bit_3_B();     // 0x58
int  test_bit_3_C();     // 0x59
int  test_bit_3_D();     // 0x5a
int  test_bit_3_E();     // 0x5b
int  test_bit_3_H();     // 0x5c
int  test_bit_3_L();     // 0x5d
int  test_bit_3_HL();    // 0x5e
int  test_bit_3_A();     // 0x5f
int  test_bit_4_B();     // 0x60
int  test_bit_4_C();     // 0x61
int  test_bit_4_D();     // 0x62
int  test_bit_4_E();     // 0x63
int  test_bit_4_H();     // 0x64
int  test_bit_4_L();     // 0x65
int  test_bit_4_HL();    // 0x66
int  test_bit_4_A();     // 0x67
int  test_bit_5_B();     // 0x68
int  test_bit_5_C();     // 0x69
int  test_bit_5_D();     // 0x6a
int  test_bit_5_E();     // 0x6b
int  test_bit_5_H();     // 0x6c
int  test_bit_5_L();     // 0x6d
int  test_bit_5_HL();    // 0x6e
int  test_bit_5_A();     // 0x6f
int  test_bit_6_B();     // 0x70
int  test_bit_6_C();     // 0x71
int  test_bit_6_D();     // 0x72
int  test_bit_6_E();     // 0x73
int  test_bit_6_H();     // 0x74
int  test_bit_6_L();     // 0x75
int  test_bit_6_HL();    // 0x76
int  test_bit_6_A();     // 0x77
int  test_bit_7_B();     // 0x78
int  test_bit_7_C();     // 0x79
int  test_bit_7_D();     // 0x7a
int  test_bit_7_E();     // 0x7b
int  test_bit_7_H();     // 0x7c
int  test_bit_7_L();     // 0x7d
int  test_bit_7_HL();    // 0x7e
int  test_bit_7_A();     // 0x7f
int  reset_bit_0_B();    // 0x80
int  reset_bit_0_C();    // 0x81
int  reset_bit_0_D();    // 0x82
int  reset_bit_0_E();    // 0x83
int  reset_bit_0_H();    // 0x84
int  reset_bit_0_L();    // 0x85
int  reset_bit_0_HL();   // 0x86
int  reset_bit_0_A();    // 0x87
int  reset_bit_1_B();    // 0x88
int  reset_bit_1_C();    // 0x89
int  reset_bit_1_D();    // 0x8a
int  reset_bit_1_E();    // 0x8b
int  reset_bit_1_H();    // 0x8c
int  reset_bit_1_L();    // 0x8d
int  reset_bit_1_HL();   // 0x8e
int  reset_bit_1_A();    // 0x8f
int  reset_bit_2_B();    // 0x90
int  reset_bit_2_C();    // 0x91
int  reset_bit_2_D();    // 0x92
int  reset_bit_2_E();    // 0x93
int  reset_bit_2_H();    // 0x94
int  reset_bit_2_L();    // 0x95
int  reset_bit_2_HL();   // 0x96
int  reset_bit_2_A();    // 0x97
int  reset_bit_3_B();    // 0x98
int  reset_bit_3_C();    // 0x99
int  reset_bit_3_D();    // 0x9a
int  reset_bit_3_E();    // 0x9b
int  reset_bit_3_H();    // 0x9c
int  reset_bit_3_L();    // 0x9d
int  reset_bit_3_HL();   // 0x9e
int  reset_bit_3_A();    // 0x9f
int  reset_bit_4_B();    // 0xa0
int  reset_bit_4_C();    // 0xa1
int  reset_bit_4_D();    // 0xa2
int  reset_bit_4_E();    // 0xa3
int  reset_bit_4_H();    // 0xa4
int  reset_bit_4_L();    // 0xa5
int  reset_bit_4_HL();   // 0xa6
int  reset_bit_4_A();    // 0xa7
int  reset_bit_5_B();    // 0xa8
int  reset_bit_5_C();    // 0xa9
int  reset_bit_5_D();    // 0xaa
int  reset_bit_5_E();    // 0xab
int  reset_bit_5_H();    // 0xac
int  reset_bit_5_L();    // 0xad
int  reset_bit_5_HL();   // 0xae
int  reset_bit_5_A();    // 0xaf
int  reset_bit_6_B();    // 0xb0
int  reset_bit_6_C();    // 0xb1
int  reset_bit_6_D();    // 0xb2
int  reset_bit_6_E();    // 0xb3
int  reset_bit_6_H();    // 0xb4
int  reset_bit_6_L();    // 0xb5
int  reset_bit_6_HL();   // 0xb6
int  reset_bit_6_A();    // 0xb7
int  reset_bit_7_B();    // 0xb8
int  reset_bit_7_C();    // 0xb9
int  reset_bit_7_D();    // 0xba
int  reset_bit_7_E();    // 0xbb
int  reset_bit_7_H();    // 0xbc
int  reset_bit_7_L();    // 0xbd
int  reset_bit_7_HL();   // 0xbe
int  reset_bit_7_A();    // 0xbf
int  set_bit_0_B();      // 0xc0
int  set_bit_0_C();      // 0xc1
int  set_bit_0_D();      // 0xc2
int  set_bit_0_E();      // 0xc3
int  set_bit_0_H();      // 0xc4
int  set_bit_0_L();      // 0xc5
int  set_bit_0_HL();     // 0xc6
int  set_bit_0_A();      // 0xc7
int  set_bit_1_B();      // 0xc8
int  set_bit_1_C();      // 0xc9
int  set_bit_1_D();      // 0xca
int  set_bit_1_E();      // 0xcb
int  set_bit_1_H();      // 0xcc
int  set_bit_1_L();      // 0xcd
int  set_bit_1_HL();     // 0xce
int  set_bit_1_A();      // 0xcf
int  set_bit_2_B();      // 0xd0
int  set_bit_2_C();      // 0xd1
int  set_bit_2_D();      // 0xd2
int  set_bit_2_E();      // 0xd3
int  set_bit_2_H();      // 0xd4
int  set_bit_2_L();      // 0xd5
int  set_bit_2_HL();     // 0xd6
int  set_bit_2_A();      // 0xd7
int  set_bit_3_B();      // 0xd8
int  set_bit_3_C();      // 0xd9
int  set_bit_3_D();      // 0xda
int  set_bit_3_E();      // 0xdb
int  set_bit_3_H();      // 0xdc
int  set_bit_3_L();      // 0xdd
int  set_bit_3_HL();     // 0xde
int  set_bit_3_A();      // 0xdf
int  set_bit_4_B();      // 0xe0
int  set_bit_4_C();      // 0xe1
int  set_bit_4_D();      // 0xe2
int  set_bit_4_E();      // 0xe3
int  set_bit_4_H();      // 0xe4
int  set_bit_4_L();      // 0xe5
int  set_bit_4_HL();     // 0xe6
int  set_bit_4_A();      // 0xe7
int  set_bit_5_B();      // 0xe8
int  set_bit_5_C();      // 0xe9
int  set_bit_5_D();      // 0xea
int  set_bit_5_E();      // 0xeb
int  set_bit_5_H();      // 0xec
int  set_bit_5_L();      // 0xed
int  set_bit_5_HL();     // 0xee
int  set_bit_5_A();      // 0xef
int  set_bit_6_B();      // 0xf0
int  set_bit_6_C();      // 0xf1
int  set_bit_6_D();      // 0xf2
int  set_bit_6_E();      // 0xf3
int  set_bit_6_H();      // 0xf4
int  set_bit_6_L();      // 0xf5
int  set_bit_6_HL();     // 0xf6
int  set_bit_6_A();      // 0xf7
int  set_bit_7_B();      // 0xf8
int  set_bit_7_C();      // 0xf9
int  set_bit_7_D();      // 0xfa
int  set_bit_7_E();      // 0xfb
int  set_bit_7_H();      // 0xfc
int  set_bit_7_L();      // 0xfd
int  set_bit_7_HL();     // 0xfe
int  set_bit_7_A();      // 0xff

//
// Extended instruction set
//

int  NOP();              // 0x00
int  LD_BC();            // 0x01
int  LD_mBC_A();         // 0x02
int  INC_BC();           // 0x03
int  INC_B();            // 0x04
int  DEC_B();            // 0x05
int  LD_B();             // 0x06
int  RLCA();             // 0x07
int  LD_a16_SP();        // 0x08
int  ADD_HL_BC();        // 0x09
int  LD_A_mBC();         // 0x0a
int  DEC_BC();           // 0x0b
int  INC_C();            // 0x0c
int  DEC_C();            // 0x0d
int  LD_C();             // 0x0e
int  RRCA();             // 0x0f
//   does not exist      // 0x10
int  LD_DE();            // 0x11
int  LD_mDE_A();         // 0x12
int  INC_DE();           // 0x13
int  INC_D();            // 0x14
int  DEC_D();            // 0x15
int  LD_D();             // 0x16
int  RLA();              // 0x17
int  JR();               // 0x18
int  ADD_HL_DE();        // 0x19
int  LD_A_mDE();         // 0x1a
int  DEC_DE();           // 0x1b
int  INC_E();            // 0x1c
int  DEC_E();            // 0x1d
int  LD_E();             // 0x1e
int  RRA();              // 0x1f
int  JR_NZ();            // 0x20
int  LD_HL();            // 0x21
int  LD_mHL_A_inc();     // 0x22
int  INC_HL();           // 0x23
int  INC_H();            // 0x24
int  DEC_H();            // 0x25
int  LD_H();             // 0x26
int  DAA();              // 0x27
int  JR_Z();             // 0x28
int  ADD_HL_HL();        // 0x29
int  LD_A_mHL_inc();     // 0x2a
int  DEC_HL();           // 0x2b
int  INC_L();            // 0x2c
int  DEC_L();            // 0x2d
int  LD_L();             // 0x2e
int  CPL();              // 0x2f
int  JR_NC();            // 0x30
int  LD_SP();            // 0x31
int  LD_mHL_A_dec();     // 0x32
int  INC_SP();           // 0x33
int  INC_mHL();          // 0x34
int  DEC_mHL();          // 0x35
int  LD_mHL();           // 0x36
int  SCF();              // 0x37
int  JR_C();             // 0x38
int  ADD_HL_SP();        // 0x39
int  LD_A_mHL_dec();     // 0x3a
int  DEC_SP();           // 0x3b
int  INC_A();            // 0x3c
int  DEC_A();            // 0x3d
int  LD_A();             // 0x3e
int  CCF();              // 0x3f
int  LD_B_B();           // 0x40
int  LD_B_C();           // 0x41
int  LD_B_D();           // 0x42
int  LD_B_E();           // 0x43
int  LD_B_H();           // 0x44
int  LD_B_L();           // 0x45
int  LD_B_mHL();         // 0x46
int  LD_B_A();           // 0x47
int  LD_C_B();           // 0x48
int  LD_C_C();           // 0x49
int  LD_C_D();           // 0x4a
int  LD_C_E();           // 0x4b
int  LD_C_H();           // 0x4c
int  LD_C_L();           // 0x4d
int  LD_C_mHL();         // 0x4e
int  LD_C_A();           // 0x4f
int  LD_D_B();           // 0x50
int  LD_D_C();           // 0x51
int  LD_D_D();           // 0x52
int  LD_D_E();           // 0x53
int  LD_D_H();           // 0x54
int  LD_D_L();           // 0x55
int  LD_D_mHL();         // 0x56
int  LD_D_A();           // 0x57
int  LD_E_B();           // 0x58
int  LD_E_C();           // 0x59
int  LD_E_D();           // 0x5a
int  LD_E_E();           // 0x5b
int  LD_E_H();           // 0x5c
int  LD_E_L();           // 0x5d
int  LD_E_mHL();         // 0x5e
int  LD_E_A();           // 0x5f
int  LD_H_B();           // 0x60
int  LD_H_C();           // 0x61
int  LD_H_D();           // 0x62
int  LD_H_E();           // 0x63
int  LD_H_H();           // 0x64
int  LD_H_L();           // 0x65
int  LD_H_mHL();         // 0x66
int  LD_H_A();           // 0x67
int  LD_L_B();           // 0x68
int  LD_L_C();           // 0x69
int  LD_L_D();           // 0x6a
int  LD_L_E();           // 0x6b
int  LD_L_H();           // 0x6c
int  LD_L_L();           // 0x6d
int  LD_L_mHL();         // 0x6e
int  LD_L_A();           // 0x6f
int  LD_mHL_B();         // 0x70
int  LD_mHL_C();         // 0x71
int  LD_mHL_D();         // 0x72
int  LD_mHL_E();         // 0x73
int  LD_mHL_H();         // 0x74
int  LD_mHL_L();         // 0x75
//   does not exist      // 0x76
int  LD_mHL_A();         // 0x77
int  LD_A_B();           // 0x78
int  LD_A_C();           // 0x79
int  LD_A_D();           // 0x7a
int  LD_A_E();           // 0x7b
int  LD_A_H();           // 0x7c
int  LD_A_L();           // 0x7d
int  LD_A_mHL();         // 0x7e
int  LD_A_A();           // 0x7f
int  ADD_A_B();          // 0x80
int  ADD_A_C();          // 0x81
int  ADD_A_D();          // 0x82
int  ADD_A_E();          // 0x83
int  ADD_A_H();          // 0x84
int  ADD_A_L();          // 0x85
int  ADD_A_mHL();        // 0x86
int  ADC_A_A();          // 0x87
int  ADC_A_B();          // 0x88
int  ADC_A_C();          // 0x89
int  ADC_A_D();          // 0x8a
int  ADC_A_E();          // 0x8b
int  ADC_A_H();          // 0x8c
int  ADC_A_L();          // 0x8d
int  ADC_A_mHL();        // 0x8e
int  ADC_A_A();          // 0x8f
int  SUB_B();            // 0x90
int  SUB_C();            // 0x91
int  SUB_D();            // 0x92
int  SUB_E();            // 0x93
int  SUB_H();            // 0x94
int  SUB_L();            // 0x95
int  SUB_mHL();          // 0x96
int  SUB_A();            // 0x97
int  SBC_B();            // 0x98
int  SBC_C();            // 0x99
int  SBC_D();            // 0x9a
int  SBC_E();            // 0x9b
int  SBC_H();            // 0x9c
int  SBC_L();            // 0x9d
int  SBC_mHL();          // 0x9e
int  SBC_A();            // 0x9f
int  AND_B();            // 0xa0
int  AND_C();            // 0xa1
int  AND_D();            // 0xa2
int  AND_E();            // 0xa3
int  AND_H();            // 0xa4
int  AND_L();            // 0xa5
int  AND_mHL();          // 0xa6
int  AND_A();            // 0xa7
int  XOR_B();            // 0xa8
int  XOR_C();            // 0xa9
int  XOR_D();            // 0xaa
int  XOR_E();            // 0xab
int  XOR_H();            // 0xac
int  XOR_L();            // 0xad
int  XOR_HL();           // 0xae
int  XOR_A();            // 0xaf
int  OR_B();             // 0xb0
int  OR_C();             // 0xb1
int  OR_D();             // 0xb2
int  OR_E();             // 0xb3
int  OR_H();             // 0xb4
int  OR_L();             // 0xb5
int  OR_mHL();           // 0xb6
int  OR_A();             // 0xb7
int  CP_B();             // 0xb8
int  CP_C();             // 0xb9
int  CP_D();             // 0xba
int  CP_E();             // 0xbb
int  CP_H();             // 0xbc
int  CP_L();             // 0xbd
int  CP_HL();            // 0xbe
int  CP_A();             // 0xbf
int  RET_NZ();           // 0xc0
int  POP_BC();           // 0xc1
int  JP_NZ();            // 0xc2
int  JP();               // 0xc3
int  CALL_NZ();          // 0xc4
int  PUSH_BC();          // 0xc5
int  ADD_A_d8();         // 0xc6
int  RST_00();           // 0xc7
int  RET_Z();            // 0xc8
int  RET();              // 0xc9
int  JP_Z();             // 0xca
//   PREFIX              // 0xcb
int  CALL_Z();           // 0xcc
int  CALL();             // 0xcd
int  ADC_A_d8();         // 0xce
int  RST_08();           // 0xcf
int  RET_NC();           // 0xd0
int  POP_DE();           // 0xd1
int  JP_NC();            // 0xd2
//   does not exist      // 0xd3
int  CALL_NC();          // 0xd4
int  PUSH_DE();          // 0xd5
int  SUB_A_d8();         // 0xd6
int  RST_10();           // 0xd7
int  RET_C();            // 0xd8
int  RETI();             // 0xd9
int  JP_C();             // 0xda
//   does not exist      // 0xdb
int  CALL_C();           // 0xdc
//   does not exist      // 0xdd
int  SBC_A_d8();         // 0xde
int  RST_18();           // 0xdf
int  LDH_a8_A();         // 0xe0
int  POP_HL();           // 0xe1
int  LD_mC_A();          // 0xe2
//   does not exist      // 0xe3
//   does not exist      // 0xe4
int  PUSH_HL();          // 0xe5
int  AND_A_d8();         // 0xe6
int  RST_20();           // 0xe7
int  ADD_SP_r8();        // 0xe8
int  JP_HL();            // 0xe9
int  LD_a16_A();         // 0xea
//   does not exist      // 0xeb
//   does not exist      // 0xec
//   does not exist      // 0xed
int  XOR_A_d8();         // 0xee
int  RST_28();           // 0xef
int  LDH_A_a8();         // 0xf0
int  POP_AF();           // 0xf1
int  LD_A_mC();          // 0xf2
int  DI();               // 0xf3
//   does not exist      // 0xf4
int  PUSH_AF();          // 0xf5
int  OR_A_d8();          // 0xf6
int  RST_30();           // 0xf7
int  LDHL_SP_r8();       // 0xf8
int  LD_SP_HL();         // 0xf9
int  LD_A_a16();         // 0xfa
int  EI();               // 0xfb
//   does not exist      // 0xfc
//   does not exist      // 0xfd
int  CP_d8();            // 0xfe
int  RST_38();           // 0xff

op prefix_operations[NUM_OPS];
op operations[NUM_OPS];

#endif
